### ISSUE TITLE
Simplify code by using projectViewNestingRulesProvider

### ISSUE THREAD

**Issue by alexander-doroshko** [stephendoyle/angulardart-folding#1]
Since version 2017.2 all JetBrains' IDEs have native support for configurable file nesting in the Project View. See [File Nesting...](https://www.jetbrains.com/help/webstorm/file-nesting-dialog.html) item on the context menu of the title bar in the Project tool window.

If you believe that installing the plugin is easier than configuring File Nesting manually then you may simplify your plugin source code by implementing `projectViewNestingRulesProvider` instead of `treeStructureProvider`. See example [here](https://github.com/JetBrains/intellij-plugins/blob/master/Dart/src/com/jetbrains/lang/dart/projectView/DartNestingRulesProvider.java).

Just an idea.

**Comment by stephendoyle** [comment]
Ah, thanks for this. I was unaware that the feature existed. I will leave this plugin as is for now, but may refactor in the future if I make further updates.
